name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build, Test, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: |
          chmod +x ./mvnw
          echo ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Build JAR file
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t myapp:${{ github.ref_name }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag quickstart:${{ github.ref_name }} ${{ secrets.DOCKER_HUB_USERNAME }}/quickstart:${{ github.ref_name }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/quickstart:${{ github.ref_name }}

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials my-cluster --zone asia-southeast1 --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Apply Kubernetes configuration
        run: |
          sed -i 's|<IMAGE_TAG>|${{ secrets.DOCKER_HUB_USERNAME }}/quickstart:${{ github.ref_name }}|g' k8s/springboot-deployment.yaml
          kubectl apply -f k8s/springboot-deployment.yaml