name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build, Test, and Push Docker Image
    environment: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: |
          chmod +x ./mvnw
          echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}"

      - name: Build JAR file
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t quickstart:${{ github.ref_name }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag quickstart:${{ github.ref_name }} ${{ secrets.DOCKER_HUB_USERNAME }}/quickstart:${{ github.ref_name }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/quickstart:${{ github.ref_name }}

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    environment: deploy
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auth GKE
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} --zone ${{ secrets.GCP_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Apply Kubernetes configuration
        run: |
          sed -i 's|<IMAGE_TAG>|${{ secrets.DOCKER_HUB_USERNAME }}/quickstart:${{ github.ref_name }}|g' springboot-deployment.yaml
          kubectl apply -f springboot-deployment.yaml